Updated Ubuntu 18.04 to latest
oneapi-src/oneTBB pull request #1047
Opened 2023-03-20 21:53 UTC by dessie-williams

### Description 
_Add a comprehensive description of proposed changes_

**I UPDATED THE CI FROM UBUNTU-18.04 TO UBUNTU-LATEST AND RAN A TEST AND IT PAST SUCCESSFULLY**
https://github.com/dessie-williams/oneTBB/actions/runs/4473018271/jobs/7859882869

Fixes # - _issue number(s) if exists_

- [ ] - git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [ ] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and some bug fixes_
- [ ] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [ ] not needed

### Breaks backward compatibility
- [ ] Yes
- [ ] No
- [ ] Unknown

### Notify the following users
_List users with `@` to send notifications_

### Other information

2023-03-21 08:09 UTC, isaevil commented
@dessie-williams was there an issue with Ubuntu 18.04?

2023-03-21 12:34 UTC, wills-int commented
> @dessie-williams was there an issue with Ubuntu 18.04?

@isaevil This was a request, put in by Timmie, to make the changes to the script and test the changes. The 18.04 will not be supported, after March.
[PREINFRA-772](https://jira.devtools.intel.com/browse/PREINFRA-772)

2023-03-21 16:35 UTC, isaevil commented on .github/workflows/ci.yml
Please, update copyright year 2022->2023

2023-03-21 17:43 UTC, wills-int commented on .github/workflows/ci.yml
@isaevil Changes have been done.

2023-03-22 14:35 UTC, isaevil requested changes

2023-03-22 14:35 UTC, isaevil commented on .github/workflows/ci.yml
> +# Copyright (c) 2022-2023 Intel Corporation
It should be 2021-2023

2023-03-22 14:38 UTC, isaevil approved these changes

2023-03-22 14:47 UTC, merged