fix deadlock in tbbmalloc raportFreeBlocks function
oneapi-src/oneTBB pull request #1117
Opened 2023-05-29 14:36 UTC by lplewa

### Description 
_Add a comprehensive description of proposed changes_

Fixes # - _issue number(s) if exists_

- [x] - git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [x] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [ ] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and some bug fixes_
- [x] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
@ldorau @KFilipek 

### Other information

2023-05-30 08:14 UTC, ldorau requested changes
@lplewa A detailed description and explanation of this fix is missing.

2023-05-30 12:52 UTC, lplewa commented
> @lplewa A detailed description and explanation of this fix is missing.

Done

2023-05-30 13:05 UTC, pavelkumbrasev commented
@lplewa I can not see description of this issue. Do I miss something?

2023-05-30 14:34 UTC, lplewa commented
> Is there a possibility to write test that will reproduce this hang and prove that this fix helps?

it is deadlock in a debug helper function, i'm not sure it is worth an effort to add test for it.

2023-06-12 13:41 UTC, KFilipek approved these changes
LGTM

2023-06-12 14:09 UTC, ldorau approved these changes
LGTM

2023-06-13 09:54 UTC, merged