Update outdated URLs in comments
oneapi-src/oneTBB pull request #1129
Opened 2023-06-12 17:52 UTC by omalyshe

### Description 
Some URLs have expired and should be replaced.

Fixes # - _issue number(s) if exists_

- [x] - git commit message contains an appropriate signed-off-by string _(see [CONTRIBUTING.md](https://github.com/oneapi-src/oneTBB/blob/master/CONTRIBUTING.md#pull-requests) for details)_

### Type of change

_Choose one or multiple, leave empty if none of the other choices apply_

_Add a respective label(s) to PR if you have permissions_

- [ ] bug fix - _change that fixes an issue_
- [ ] new feature - _change that adds functionality_
- [ ] tests - _change in tests_
- [ ] infrastructure - _change in infrastructure and CI_
- [x] documentation - _documentation update_

### Tests

- [ ] added - _required for new features and some bug fixes_
- [x] not needed

### Documentation

- [ ] updated in # - _add PR number_
- [ ] needs to be updated
- [x] not needed

### Breaks backward compatibility
- [ ] Yes
- [x] No
- [ ] Unknown

### Notify the following users
_List users with `@` to send notifications_

### Other information

2023-06-13 00:01 UTC, dnmokhov requested changes

2023-06-13 00:01 UTC, dnmokhov commented on examples/getting_started/sub_string_finder/README.md
> +An example that uses the `parallel_for` template in a substring matching program. The [oneAPI Threading Building Blocks [](https://www.intel.com/content/www/us/en/docs/onetbb/get-started-guide/curren
```suggestion
An example that uses the `parallel_for` template in a substring matching program. The [oneAPI Threading Building Blocks Get Started Guide](https://www.intel.com/content/www/us/en/docs/onetbb/get-started-guide/current/overview.html) describes this example.
```

2023-06-15 10:31 UTC, alexandraepan submitted a review, later dismissed
LGTM!

2023-06-15 13:45 UTC, omalyshe commented
@dnmokhov @alexandraepan Please, look. I completed fixes.

2023-06-15 14:56 UTC, dnmokhov approved these changes
LGTM

2023-06-19 09:44 UTC, merged